//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int student_Id { get; set; }
        public string student_name { get; set; }
        public int course_Id { get; set; }
        public string course_name { get; set; }
    
        public virtual cours cours { get; set; }
    }
}
